apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qwhbseoa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-qwhbseoa:b940ffc7e5d892fe27c6602664a245bb3d861cee@sha256:9c015bfec6fbf96ee65990ba63d78bf6c8d90ed1259bbba665d1ce4989723777
          name: container-image
